Update release.yml
- Add R2021b and R2022a to test matrix
- Support workflow dispatch event
- Skip code coverage upload

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -8,16 +8,36 @@ on:
   push:
     tags: 
       - 'v*'
+  workflow_dispatch:
+    inputs:
+      version:
+        description: 'Version number in major.minor.patch format, i.e 2.8.0'
+        required: true
+        type: string
 
 jobs:
   # This workflow contains:
-  # 1. a matrixed test job run across a bunch of releases of MATLAB
+  # 1. a matrixed test job run across MATLAB releases from R2021b to R2024b
   # 2. a reporting job that summarizes the tests, and updates release badge
+  
+  validate_version:
+    runs-on: ubuntu-latest
+    if: github.event_name == workflow_dispatch
+    steps:
+      - name: Check version format
+        run: |
+          version="${{ github.event.inputs.version }}"
+          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Input for 'version' ('$version') is not in the expected major.minor.patch format."
+            exit 1
+          fi
+          echo "Version '$version' is valid."
+
   test:
     strategy:
       fail-fast: false
       matrix:
-        MATLABVersion: [R2022b, R2023a, R2023b, R2024a, R2024b]
+        MATLABVersion: [R2021b, R2022a, R2022b, R2023a, R2023b, R2024a, R2024b]
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
@@ -38,15 +58,6 @@ jobs:
           command: |
             addpath(genpath("tools"));
             testToolbox('ReportSubdirectory',"${{ matrix.MATLABVersion }}", 'CreateBadge', false)     
-
-      # Upload code coverage information to Codecov
-      - name: Upload code coverage report to Codecov (https://app.codecov.io/gh/openMetadataInitiative/openMINDS_MATLAB)
-        uses: codecov/codecov-action@v4
-        if: always()
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          files: docs/reports/codecoverage.xml
-          env_vars: ${{ matrix.MATLABVersion }}
 
       # Save the contents of the report directory from each release into an artifact.
       - name: Save report directory
